name: Pipeline

on:
  push:
    branches:
      - develop
      #- release
      #- main
  #pull_request:
  #  types:
  #    - opened
  #    - synchronize
  #    - reopened
  #  branches:
      #- develop
      #- release
      #- main

env:
  MODULE: lb-kinesis-send
  SERVICE_MODULE: lb-kinesis-send
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #NODEJS_VERSION: node:14.19.3-alpine3.16
  NODEJS_VERSION: 14

jobs:
  deploy:
    name: Default
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: yarn install

    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        #SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}